### ISSUE TITLE
LDAPS?

### ISSUE THREAD

**Issue by tristani** [feathersjs-ecosystem/feathers-authentication-ldap#18]
Im trying to use ldaps but it throws an error: 

Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1108:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38)

**Comment by Maryem44** [comment]
Is this problem still same till now?

**Comment by Maryem44** [comment]
Hello I found solution for this problem this package handls asyncOptions so you can add as an option 
 tlsOptions:{rejectUnauthorized: false} and this will resolve the problem
